import {
  HiOutlineViewGrid,
  HiOutlineMap,
  HiOutlineGlobe,
  HiOutlineClock,
  HiOutlineCog,
} from 'react-icons/hi'
import { BookmarkIcon } from '@/components/icons'

export const SIDEBAR_NAV = [
  { id: 'dashboard', label: 'Dashboard', icon: HiOutlineViewGrid },
  { id: 'trips', label: 'My Trips', icon: HiOutlineMap },
  { id: 'history', label: 'History', icon: HiOutlineClock },
  { id: 'explore', label: 'Explore', icon: HiOutlineGlobe },
  { id: 'saved', label: 'Saved Plans', icon: BookmarkIcon },
  { id: 'settings', label: 'Settings', icon: HiOutlineCog },
]

export const TRAVEL_STYLES = [
  { value: 'budget', label: 'Budget', api: 'budget' },
  { value: 'backpacker', label: 'Backpacker', api: 'budget' },
  { value: 'comfort', label: 'Comfort', api: 'comfort' },
  { value: 'luxury', label: 'Luxury', api: 'luxury' },
  { value: 'adventure', label: 'Adventure', api: 'balanced' },
  { value: 'business', label: 'Business', api: 'comfort' },
  { value: 'family', label: 'Family', api: 'balanced' },
  { value: 'romantic', label: 'Romantic', api: 'luxury' },
  { value: 'solo', label: 'Solo', api: 'balanced' },
]

export const INTEREST_OPTIONS = [
  'Food',
  'Nature',
  'Museums',
  'Nightlife',
  'Shopping',
  'Photography',
  'Adventure',
  'History',
  'Culture',
  'Beach',
  'Mountains',
]

/** Map UI interests → backend-accepted values */
export const INTEREST_API_MAP = {
  Food: 'Food',
  Nature: 'Nature',
  Museums: 'Culture',
  Nightlife: 'Nightlife',
  Shopping: 'Culture',
  Photography: 'Nature',
  Adventure: 'Adventure',
  History: 'Culture',
  Culture: 'Culture',
  Beach: 'Nature',
  Mountains: 'Nature',
  Relaxation: 'Relaxation',
}

export const ACCOMMODATION_OPTIONS = [
  'Hostel',
  'Hotel',
  'Luxury Hotel',
  'Apartment',
  'Resort',
]

export const TRANSPORT_OPTIONS = [
  'Public',
  'Rental Car',
  'Walking',
  'Private Taxi',
  'Mixed',
]

/** Free-form prompt chips — append into “Describe your trip” */
export const PROMPT_SUGGESTIONS = [
  {
    id: 'budget',
    label: 'Budget',
    text: 'Stay within my budget and prefer affordable food, stays, and transport.',
  },
  {
    id: 'days',
    label: 'Days',
    text: 'Pace each day realistically — not rushed, with short travel times between stops.',
  },
  {
    id: 'famous',
    label: 'Most Famous places',
    text: 'Prioritize the most famous must-see landmarks and iconic attractions.',
  },
]

export const CURRENCY_OPTIONS = [
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen' },
  { code: 'KRW', symbol: '₩', name: 'South Korean Won' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar' },
  { code: 'CAD', symbol: 'C$', name: 'Canadian Dollar' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar' },
  { code: 'THB', symbol: '฿', name: 'Thai Baht' },
  { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
]

/**
 * Daily cost baselines in INR per traveler for budget intelligence.
 * Multiplied by days × travelers × style multiplier.
 */
export const STYLE_BUDGET_MULT = {
  budget: 0.7,
  backpacker: 0.55,
  comfort: 1.15,
  luxury: 2.4,
  adventure: 1.2,
  business: 1.6,
  family: 1.25,
  romantic: 1.9,
  solo: 1.0,
}

export const EXPLORE_REGIONS = [
  { id: 'all', label: 'All' },
  { id: 'asia', label: 'Asia' },
  { id: 'europe', label: 'Europe' },
  { id: 'america', label: 'America' },
  { id: 'africa', label: 'Africa' },
  { id: 'oceania', label: 'Oceania' },
  { id: 'middle-east', label: 'Middle East' },
]

export const EXPLORE_SECTIONS = [
  { id: 'popular', label: 'Popular Destinations' },
  { id: 'trending', label: 'Trending This Month' },
  { id: 'budget', label: 'Budget Friendly' },
  { id: 'luxury', label: 'Luxury' },
  { id: 'adventure', label: 'Adventure' },
  { id: 'beach', label: 'Beach' },
  { id: 'mountain', label: 'Mountain' },
]

export const COUNTRIES = [
  {
    id: 'japan',
    name: 'Japan',
    capital: 'Tokyo',
    flag: '🇯🇵',
    region: 'asia',
    categories: ['popular', 'trending', 'adventure', 'mountain'],
    topAttraction: 'Mount Fuji',
    timezone: 'GMT+9',
    currency: 'JPY',
    currencySymbol: '¥',
    language: 'Japanese',
    bestSeason: 'Mar–May · Oct–Nov',
    avgCostPerDay: 12000,
    weather: '18°C · Clear',
    image:
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Fushimi Inari', 'Shibuya Crossing', 'Arashiyama Bamboo', 'Mount Fuji'],
    aliases: ['japan', 'tokyo', 'kyoto', 'osaka'],
  },
  {
    id: 'south-korea',
    name: 'South Korea',
    capital: 'Seoul',
    flag: '🇰🇷',
    region: 'asia',
    categories: ['popular', 'trending'],
    topAttraction: 'Gyeongbokgung Palace',
    timezone: 'GMT+9',
    currency: 'KRW',
    currencySymbol: '₩',
    language: 'Korean',
    bestSeason: 'Apr–Jun · Sep–Oct',
    avgCostPerDay: 9000,
    weather: '16°C · Mild',
    image:
      'https://images.unsplash.com/photo-1517154421773-0529f29ea451?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Gyeongbokgung', 'Bukchon Hanok', 'N Seoul Tower', 'Jeju Island'],
    aliases: ['korea', 'south korea', 'seoul', 'busan'],
  },
  {
    id: 'france',
    name: 'France',
    capital: 'Paris',
    flag: '🇫🇷',
    region: 'europe',
    categories: ['popular', 'luxury'],
    topAttraction: 'Eiffel Tower',
    timezone: 'GMT+1',
    currency: 'EUR',
    currencySymbol: '€',
    language: 'French',
    bestSeason: 'Apr–Jun · Sep–Oct',
    avgCostPerDay: 14000,
    weather: '14°C · Partly cloudy',
    image:
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Eiffel Tower', 'Louvre', 'Montmartre', 'French Riviera'],
    aliases: ['france', 'paris', 'lyon', 'nice'],
  },
  {
    id: 'italy',
    name: 'Italy',
    capital: 'Rome',
    flag: '🇮🇹',
    region: 'europe',
    categories: ['popular', 'luxury'],
    topAttraction: 'Colosseum',
    timezone: 'GMT+1',
    currency: 'EUR',
    currencySymbol: '€',
    language: 'Italian',
    bestSeason: 'Apr–Jun · Sep–Oct',
    avgCostPerDay: 13000,
    weather: '20°C · Sunny',
    image:
      'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Colosseum', 'Venice Canals', 'Amalfi Coast', 'Florence Duomo'],
    aliases: ['italy', 'rome', 'venice', 'milan', 'florence'],
  },
  {
    id: 'usa',
    name: 'USA',
    capital: 'Washington, D.C.',
    flag: '🇺🇸',
    region: 'america',
    categories: ['popular', 'adventure'],
    topAttraction: 'Grand Canyon',
    timezone: 'GMT−5 to −10',
    currency: 'USD',
    currencySymbol: '$',
    language: 'English',
    bestSeason: 'May–Sep',
    avgCostPerDay: 16000,
    weather: '22°C · Clear',
    image:
      'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?auto=format&fit=crop&w=1200&q=80',
    attractions: ['NYC Skyline', 'Grand Canyon', 'Golden Gate', 'Walt Disney World'],
    aliases: ['usa', 'united states', 'america', 'new york', 'nyc', 'la', 'california'],
  },
  {
    id: 'uae',
    name: 'United Arab Emirates',
    capital: 'Abu Dhabi',
    flag: '🇦🇪',
    region: 'middle-east',
    categories: ['trending', 'luxury', 'adventure'],
    topAttraction: 'Burj Khalifa',
    timezone: 'GMT+4',
    currency: 'AED',
    currencySymbol: 'د.إ',
    language: 'Arabic',
    bestSeason: 'Nov–Mar',
    avgCostPerDay: 15000,
    weather: '32°C · Sunny',
    image:
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Burj Khalifa', 'Sheikh Zayed Mosque', 'Palm Jumeirah', 'Desert Safari'],
    aliases: ['uae', 'dubai', 'abu dhabi', 'emirates'],
  },
  {
    id: 'thailand',
    name: 'Thailand',
    capital: 'Bangkok',
    flag: '🇹🇭',
    region: 'asia',
    categories: ['popular', 'budget', 'beach'],
    topAttraction: 'Phi Phi Islands',
    timezone: 'GMT+7',
    currency: 'THB',
    currencySymbol: '฿',
    language: 'Thai',
    bestSeason: 'Nov–Feb',
    avgCostPerDay: 5500,
    weather: '30°C · Humid',
    image:
      'https://images.unsplash.com/photo-1528181304800-259b08848526?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Grand Palace', 'Chiang Mai Temples', 'Phi Phi Islands', 'Ayutthaya'],
    aliases: ['thailand', 'bangkok', 'phuket', 'chiang mai'],
  },
  {
    id: 'switzerland',
    name: 'Switzerland',
    capital: 'Bern',
    flag: '🇨🇭',
    region: 'europe',
    categories: ['luxury', 'mountain', 'adventure'],
    topAttraction: 'Matterhorn',
    timezone: 'GMT+1',
    currency: 'CHF',
    currencySymbol: 'CHF',
    language: 'German · French · Italian',
    bestSeason: 'Jun–Sep',
    avgCostPerDay: 18000,
    weather: '12°C · Crisp',
    image:
      'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Matterhorn', 'Lake Geneva', 'Jungfraujoch', 'Lucerne'],
    aliases: ['switzerland', 'zurich', 'geneva', 'interlaken'],
  },
  {
    id: 'spain',
    name: 'Spain',
    capital: 'Madrid',
    flag: '🇪🇸',
    region: 'europe',
    categories: ['popular', 'beach'],
    topAttraction: 'Sagrada Família',
    timezone: 'GMT+1',
    currency: 'EUR',
    currencySymbol: '€',
    language: 'Spanish',
    bestSeason: 'Apr–Jun · Sep–Oct',
    avgCostPerDay: 11000,
    weather: '21°C · Bright',
    image:
      'https://images.unsplash.com/photo-1543783207-ec64e4d93334?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Sagrada Família', 'Alhambra', 'Park Güell', 'Ibiza'],
    aliases: ['spain', 'barcelona', 'madrid', 'seville'],
  },
  {
    id: 'indonesia',
    name: 'Indonesia',
    capital: 'Jakarta',
    flag: '🇮🇩',
    region: 'asia',
    categories: ['trending', 'budget', 'beach', 'adventure'],
    topAttraction: 'Ubud Rice Terraces',
    timezone: 'GMT+7',
    currency: 'IDR',
    currencySymbol: 'Rp',
    language: 'Indonesian',
    bestSeason: 'Apr–Oct',
    avgCostPerDay: 6000,
    weather: '28°C · Tropical',
    image:
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Ubud Rice Terraces', 'Tanah Lot', 'Komodo', 'Borobudur'],
    aliases: ['indonesia', 'bali', 'jakarta', 'ubud'],
  },
  {
    id: 'india',
    name: 'India',
    capital: 'New Delhi',
    flag: '🇮🇳',
    region: 'asia',
    categories: ['budget', 'adventure'],
    topAttraction: 'Taj Mahal',
    timezone: 'GMT+5:30',
    currency: 'INR',
    currencySymbol: '₹',
    language: 'Hindi · English',
    bestSeason: 'Oct–Mar',
    avgCostPerDay: 4500,
    weather: '26°C · Warm',
    image:
      'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Taj Mahal', 'Jaipur Forts', 'Kerala Backwaters', 'Varanasi Ghats'],
    aliases: ['india', 'delhi', 'mumbai', 'jaipur', 'goa', 'kerala'],
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    capital: 'London',
    flag: '🇬🇧',
    region: 'europe',
    categories: ['popular'],
    topAttraction: 'Big Ben',
    timezone: 'GMT',
    currency: 'GBP',
    currencySymbol: '£',
    language: 'English',
    bestSeason: 'May–Sep',
    avgCostPerDay: 15000,
    weather: '11°C · Overcast',
    image:
      'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Big Ben', 'Stonehenge', 'Edinburgh Castle', 'Lake District'],
    aliases: ['uk', 'united kingdom', 'england', 'london', 'scotland'],
  },
  {
    id: 'morocco',
    name: 'Morocco',
    capital: 'Marrakech',
    flag: '🇲🇦',
    region: 'africa',
    categories: ['trending', 'budget', 'adventure'],
    topAttraction: 'Sahara Desert',
    timezone: 'GMT',
    currency: 'MAD',
    currencySymbol: 'د.م.',
    language: 'Arabic · French',
    bestSeason: 'Mar–May · Sep–Nov',
    avgCostPerDay: 5000,
    weather: '24°C · Sunny',
    image:
      'https://images.unsplash.com/photo-1489745428494-40f445ae95fc?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Sahara Desert', 'Marrakech Medina', 'Chefchaouen', 'Fes El Bali'],
    aliases: ['morocco', 'marrakech', 'casablanca', 'fes'],
  },
  {
    id: 'australia',
    name: 'Australia',
    capital: 'Canberra',
    flag: '🇦🇺',
    region: 'oceania',
    categories: ['popular', 'beach', 'adventure'],
    topAttraction: 'Great Barrier Reef',
    timezone: 'GMT+10',
    currency: 'AUD',
    currencySymbol: 'A$',
    language: 'English',
    bestSeason: 'Sep–Nov · Mar–May',
    avgCostPerDay: 14000,
    weather: '22°C · Bright',
    image:
      'https://images.unsplash.com/photo-1523482580670-1c738a4dc1af?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Great Barrier Reef', 'Sydney Opera House', 'Uluru', 'Great Ocean Road'],
    aliases: ['australia', 'sydney', 'melbourne', 'brisbane'],
  },
  {
    id: 'egypt',
    name: 'Egypt',
    capital: 'Cairo',
    flag: '🇪🇬',
    region: 'africa',
    categories: ['popular', 'adventure'],
    topAttraction: 'Pyramids of Giza',
    timezone: 'GMT+2',
    currency: 'EGP',
    currencySymbol: 'E£',
    language: 'Arabic',
    bestSeason: 'Oct–Apr',
    avgCostPerDay: 5500,
    weather: '28°C · Dry',
    image:
      'https://images.unsplash.com/photo-1572252009281-566001d68869?auto=format&fit=crop&w=1200&q=80',
    attractions: ['Pyramids of Giza', 'Valley of the Kings', 'Nile Cruise', 'Karnak Temple'],
    aliases: ['egypt', 'cairo', 'luxor', 'giza'],
  },
]

export const PACKING_DEFAULTS = [
  'Passport & visas',
  'Travel adapter',
  'Comfortable walking shoes',
  'Weather-ready layers',
  'Portable charger',
  'Local currency / cards',
  'Medications & first aid',
  'Reusable water bottle',
]

export const GENERATION_STEPS = [
  'Analyzing destination...',
  'Mapping local vibes...',
  'Finding attractions...',
  'Curating restaurants...',
  'Optimizing budget...',
  'Balancing your schedule...',
  'Creating itinerary...',
  'Polishing your trip plan...',
]
