/** Open a print-friendly window for trip PDF export. */
export function downloadTripPdf(trip) {
  const data = trip.data ?? trip
  const days = data.days ?? []

  const daysHtml = days
    .map(
      (day) => `
      <section style="margin-bottom:24px;page-break-inside:avoid;">
        <h3 style="margin:0 0 8px;font-size:16px;">Day ${day.day}: ${day.title}</h3>
        <p style="margin:0 0 12px;color:#666;font-size:13px;">${day.theme ?? ''}</p>
        <ul style="margin:0;padding-left:20px;">
          ${(day.stops ?? [])
            .map(
              (stop) =>
                `<li style="margin-bottom:6px;font-size:13px;"><strong>${stop.time}</strong> — ${stop.name} <span style="color:#888;">(${stop.type})</span></li>`,
            )
            .join('')}
        </ul>
      </section>`,
    )
    .join('')

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${trip.title} — Gilora</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 720px; margin: 40px auto; padding: 0 24px; color: #111; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
    .summary { background: #fafafa; padding: 16px; border-radius: 8px; margin-bottom: 24px; font-size: 14px; line-height: 1.6; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <h1>${trip.title}</h1>
  <p class="meta">${trip.destination} · ${trip.days} days · ${trip.travellers} travellers · ${trip.budgetFormatted}</p>
  ${data.summary ? `<div class="summary">${data.summary}</div>` : ''}
  ${daysHtml}
  <p style="margin-top:32px;font-size:11px;color:#999;">Generated by Gilora</p>
</body>
</html>`

  const win = window.open('', '_blank')
  if (!win) return
  win.document.write(html)
  win.document.close()
  win.onload = () => {
    win.print()
  }
}

export async function shareTrip(trip) {
  const url = `${window.location.origin}/dashboard/trip/${trip.id}`
  const shareData = {
    title: trip.title,
    text: `Check out my ${trip.destination} trip on Gilora`,
    url,
  }

  if (navigator.share) {
    try {
      await navigator.share(shareData)
      return
    } catch {
      // fall through to clipboard
    }
  }

  await navigator.clipboard.writeText(url)
}
